"""
SIMULATED BANKING DATA — FOR DEMONSTRATION PURPOSES ONLY
=========================================================
This module operates on a local SQLite database containing DUMMY / FAKE
account data generated by seed_accounts.py.

No real customer data, real account numbers, real PINs, or real financial
information is stored or processed anywhere in this system.

Modelled loosely on Open Banking concepts for educational demonstration.
NOT connected to any real banking system, payment network, or financial API.
"""

import os
import sqlite3
import bcrypt
from datetime import datetime, timedelta

_DB_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "accounts.db"
)

_MAX_ATTEMPTS   = 5      # failed PINs before lockout
_LOCKOUT_MINS   = 15     # lockout duration in minutes


# ── connection ────────────────────────────────────────────────────────────────

def _conn():
    c = sqlite3.connect(_DB_PATH)
    c.row_factory = sqlite3.Row
    return c


# ── schema ────────────────────────────────────────────────────────────────────

def init_accounts_db():
    with _conn() as c:
        c.execute("""
            CREATE TABLE IF NOT EXISTS accounts (
                customer_id   TEXT PRIMARY KEY,
                name          TEXT NOT NULL,
                account_no    TEXT NOT NULL UNIQUE,
                balance       REAL NOT NULL DEFAULT 0.0,
                account_type  TEXT NOT NULL DEFAULT 'Checking',
                last_txn_date TEXT,
                pin_hash      TEXT NOT NULL
            )
        """)
        c.execute("""
            CREATE TABLE IF NOT EXISTS transactions (
                txn_id      TEXT PRIMARY KEY,
                customer_id TEXT NOT NULL,
                date        TEXT NOT NULL,
                description TEXT NOT NULL,
                amount      REAL NOT NULL,
                txn_type    TEXT NOT NULL CHECK (txn_type IN ('credit','debit')),
                FOREIGN KEY (customer_id) REFERENCES accounts(customer_id)
            )
        """)
        # Tracks failed PIN attempts per customer_id for lockout enforcement.
        # Timestamps stored as ISO-8601 strings — no customer PII here.
        c.execute("""
            CREATE TABLE IF NOT EXISTS login_attempts (
                id          INTEGER PRIMARY KEY AUTOINCREMENT,
                customer_id TEXT NOT NULL,
                timestamp   TEXT NOT NULL,
                success     INTEGER NOT NULL DEFAULT 0
            )
        """)
        c.execute("CREATE INDEX IF NOT EXISTS idx_attempts_cid ON login_attempts(customer_id)")
        c.commit()


# ── lockout helpers ───────────────────────────────────────────────────────────

def _is_locked_out(customer_id: str) -> bool:
    cutoff = (datetime.now() - timedelta(minutes=_LOCKOUT_MINS)).isoformat()
    with _conn() as c:
        row = c.execute(
            "SELECT COUNT(*) FROM login_attempts "
            "WHERE customer_id = ? AND success = 0 AND timestamp > ?",
            (customer_id, cutoff),   # parameterized — no injection risk
        ).fetchone()
    return row[0] >= _MAX_ATTEMPTS


def _record_attempt(customer_id: str, success: bool):
    with _conn() as c:
        c.execute(
            "INSERT INTO login_attempts (customer_id, timestamp, success) VALUES (?, ?, ?)",
            (customer_id, datetime.now().isoformat(), int(success)),
        )
        c.commit()


# ── authentication ────────────────────────────────────────────────────────────

def verify_pin(customer_id: str, pin: str) -> dict:
    """Verify a customer PIN.

    Security properties:
    - Returns the same generic message whether customer_id doesn't exist OR pin is wrong.
      This prevents user-enumeration attacks.
    - PIN is never logged or stored; only the bcrypt hash is read for comparison.
    - Lockout fires after _MAX_ATTEMPTS failures in _LOCKOUT_MINS minutes.

    Returns: {'success': bool, 'locked': bool, 'message': str, 'name': str|None}
    """
    if _is_locked_out(customer_id):
        return {
            "success": False,
            "locked": True,
            "name": None,
            "message": (
                f"Too many failed attempts. "
                f"Please try again in {_LOCKOUT_MINS} minutes."
            ),
        }

    with _conn() as c:
        row = c.execute(
            # Parameterized query — customer_id from caller, never from user chat message
            "SELECT pin_hash, name FROM accounts WHERE customer_id = ?",
            (customer_id,),
        ).fetchone()

    _GENERIC_ERROR = "Invalid credentials. Please check your Customer ID and PIN."

    if row is None:
        # Record a failure even when ID doesn't exist to prevent timing-based enumeration
        _record_attempt(customer_id, False)
        return {"success": False, "locked": False, "name": None, "message": _GENERIC_ERROR}

    # bcrypt.checkpw raises no exceptions on wrong password — returns False
    if bcrypt.checkpw(pin.encode("utf-8"), row["pin_hash"].encode("utf-8")):
        _record_attempt(customer_id, True)
        return {"success": True, "locked": False, "name": row["name"], "message": ""}
    else:
        _record_attempt(customer_id, False)
        return {"success": False, "locked": False, "name": None, "message": _GENERIC_ERROR}


# ── account queries ───────────────────────────────────────────────────────────

def get_account_info(customer_id: str) -> dict | None:
    """Return public account info for an authenticated customer.

    Account number is ALWAYS returned masked — only the last 4 digits are exposed.
    The full account_no and pin_hash are never included in the returned dict.
    """
    with _conn() as c:
        row = c.execute(
            "SELECT customer_id, name, account_no, balance, account_type, last_txn_date "
            "FROM accounts WHERE customer_id = ?",
            (customer_id,),
        ).fetchone()

    if row is None:
        return None

    return {
        "customer_id":      row["customer_id"],
        "name":             row["name"],
        "masked_account_no": "**** " + row["account_no"][-4:],
        "balance":          row["balance"],
        "account_type":     row["account_type"],
        "last_txn_date":    row["last_txn_date"],
    }


def get_transactions(customer_id: str, limit: int = 5) -> list[dict]:
    """Return the most recent transactions for an authenticated customer."""
    with _conn() as c:
        rows = c.execute(
            "SELECT txn_id, date, description, amount, txn_type "
            "FROM transactions WHERE customer_id = ? "
            "ORDER BY date DESC LIMIT ?",
            (customer_id, min(limit, 20)),  # cap at 20 to prevent large payloads
        ).fetchall()
    return [dict(r) for r in rows]


# ── demo account creation (signup) ────────────────────────────────────────────

def create_demo_account(name: str, customer_id: str, pin: str) -> dict:
    """Create a new simulated demo account.

    PIN is hashed with bcrypt before storage — plaintext PIN is discarded immediately.
    Starting balance is a fixed demo amount of $1,000.00.
    """
    import random, string

    # Server-side validation (client also validates, but never trust client alone)
    if not name or len(name) > 100:
        return {"success": False, "message": "Invalid name."}
    if not customer_id or not customer_id.isalnum() or not (3 <= len(customer_id) <= 15):
        return {"success": False, "message": "Customer ID must be 3–15 alphanumeric characters."}
    if not pin.isdigit() or not (4 <= len(pin) <= 6):
        return {"success": False, "message": "PIN must be 4–6 digits."}

    pin_hash = bcrypt.hashpw(pin.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")
    # Simulated 8-digit account number — clearly not a real bank account number
    account_no = "DEMO" + "".join(random.choices(string.digits, k=8))
    today = datetime.now().strftime("%Y-%m-%d")

    try:
        with _conn() as c:
            c.execute(
                "INSERT INTO accounts "
                "(customer_id, name, account_no, balance, account_type, last_txn_date, pin_hash) "
                "VALUES (?, ?, ?, ?, ?, ?, ?)",
                (customer_id, name, account_no, 1000.00, "Checking", today, pin_hash),
            )
            c.commit()
        return {"success": True, "customer_id": customer_id}
    except sqlite3.IntegrityError:
        return {"success": False, "message": "That Customer ID is already taken. Please choose another."}
