"""
SIMULATED BANKING SERVICES DATA — FOR DEMONSTRATION PURPOSES ONLY
==================================================================
This module operates on a local SQLite database containing DUMMY / FAKE
rate cards and customer product records generated by seed_services.py.

INFORMATION BOUNDARY: This module is READ-ONLY. It provides rate lookups and
customer record queries. It never executes any financial transaction, disbursement,
application approval, or record modification of any kind.

No real customer data, real rates, or real financial information is stored here.
All values are simulated for academic / demonstration purposes only.
"""

import os
import sqlite3

_DB_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "services.db"
)


def _conn():
    c = sqlite3.connect(_DB_PATH)
    c.row_factory = sqlite3.Row
    return c


# ── schema ────────────────────────────────────────────────────────────────────

def init_services_db():
    with _conn() as c:
        # Rate cards (bank-wide, no customer data) ────────────────────────────
        c.execute("""
            CREATE TABLE IF NOT EXISTS fd_rates (
                tenure_months                 INTEGER PRIMARY KEY,
                annual_rate                   REAL NOT NULL,
                early_withdrawal_penalty_rate REAL NOT NULL
            )
        """)
        c.execute("""
            CREATE TABLE IF NOT EXISTS loan_rates (
                loan_type         TEXT PRIMARY KEY,
                annual_rate       REAL NOT NULL,
                max_tenure_months INTEGER NOT NULL
            )
        """)
        c.execute("""
            CREATE TABLE IF NOT EXISTS pawning_rates (
                carat                 INTEGER PRIMARY KEY,
                rate_per_gram         REAL NOT NULL,
                ltv_percent           REAL NOT NULL,
                monthly_interest_rate REAL NOT NULL
            )
        """)
        c.execute("""
            CREATE TABLE IF NOT EXISTS transfer_fees (
                id            INTEGER PRIMARY KEY AUTOINCREMENT,
                transfer_type TEXT NOT NULL,
                min_amount    REAL NOT NULL,
                max_amount    REAL,
                fee_type      TEXT NOT NULL CHECK (fee_type IN ('fixed', 'percent')),
                fee_value     REAL NOT NULL,
                min_fee       REAL,
                currency      TEXT NOT NULL DEFAULT 'LKR'
            )
        """)
        c.execute("""
            CREATE TABLE IF NOT EXISTS fx_rates (
                currency_code TEXT PRIMARY KEY,
                rate_to_lkr   REAL NOT NULL,
                updated_date  TEXT NOT NULL
            )
        """)

        # Customer product records (READ-ONLY after seeding) ─────────────────
        c.execute("""
            CREATE TABLE IF NOT EXISTS fixed_deposits (
                fd_id           TEXT PRIMARY KEY,
                customer_id     TEXT NOT NULL,
                principal       REAL NOT NULL,
                tenure_months   INTEGER NOT NULL,
                annual_rate     REAL NOT NULL,
                start_date      TEXT NOT NULL,
                maturity_date   TEXT NOT NULL,
                maturity_amount REAL NOT NULL,
                status          TEXT NOT NULL CHECK (status IN ('active','matured','withdrawn'))
            )
        """)
        c.execute("""
            CREATE TABLE IF NOT EXISTS loans (
                loan_id             TEXT PRIMARY KEY,
                customer_id         TEXT NOT NULL,
                loan_type           TEXT NOT NULL,
                principal           REAL NOT NULL,
                outstanding_balance REAL NOT NULL,
                monthly_installment REAL NOT NULL,
                tenure_months       INTEGER NOT NULL,
                start_date          TEXT NOT NULL
            )
        """)
        c.execute("""
            CREATE TABLE IF NOT EXISTS pawning_records (
                pawn_id          TEXT PRIMARY KEY,
                customer_id      TEXT NOT NULL,
                item_description TEXT NOT NULL,
                weight_grams     REAL NOT NULL,
                carat            INTEGER NOT NULL,
                advance_amount   REAL NOT NULL,
                interest_rate    REAL NOT NULL,
                pawn_date        TEXT NOT NULL,
                due_date         TEXT NOT NULL,
                status           TEXT NOT NULL CHECK (status IN ('active','redeemed','forfeited'))
            )
        """)
        c.execute("""
            CREATE TABLE IF NOT EXISTS cards (
                card_id         TEXT PRIMARY KEY,
                customer_id     TEXT NOT NULL,
                card_type       TEXT NOT NULL CHECK (card_type IN ('debit','credit','prepaid')),
                masked_number   TEXT NOT NULL,
                credit_limit    REAL,
                available_limit REAL,
                status          TEXT NOT NULL CHECK (status IN ('active','blocked','expired'))
            )
        """)

        c.execute("CREATE INDEX IF NOT EXISTS idx_fd_cid ON fixed_deposits(customer_id)")
        c.execute("CREATE INDEX IF NOT EXISTS idx_ln_cid ON loans(customer_id)")
        c.execute("CREATE INDEX IF NOT EXISTS idx_pw_cid ON pawning_records(customer_id)")
        c.execute("CREATE INDEX IF NOT EXISTS idx_cd_cid ON cards(customer_id)")
        c.commit()


# ── rate card lookups (no customer_id, no auth required) ─────────────────────

def get_fd_rate(tenure_months: int) -> dict | None:
    """Return the FD rate for the nearest available tenure bracket.

    Uses ABS difference so '9 months' → '6-month bracket' or '12-month bracket'.
    Returns None only if the table is empty (should never happen after seeding).
    """
    with _conn() as c:
        row = c.execute(
            "SELECT tenure_months, annual_rate, early_withdrawal_penalty_rate "
            "FROM fd_rates ORDER BY ABS(tenure_months - ?) LIMIT 1",
            (tenure_months,),
        ).fetchone()
    return dict(row) if row else None


def get_loan_rate(loan_type: str) -> dict | None:
    """Return the loan rate for a specific loan type (exact match, case-insensitive)."""
    with _conn() as c:
        row = c.execute(
            "SELECT loan_type, annual_rate, max_tenure_months "
            "FROM loan_rates WHERE loan_type = ?",
            (loan_type.lower(),),
        ).fetchone()
    return dict(row) if row else None


def get_pawning_rate(carat: int) -> dict | None:
    """Return the pawning rate for a given gold carat (18, 22, or 24)."""
    with _conn() as c:
        row = c.execute(
            "SELECT carat, rate_per_gram, ltv_percent, monthly_interest_rate "
            "FROM pawning_rates WHERE carat = ?",
            (carat,),
        ).fetchone()
    return dict(row) if row else None


def get_transfer_fee(transfer_type: str, amount: float) -> dict | None:
    """Return the applicable fee row for a given transfer type and amount."""
    with _conn() as c:
        row = c.execute(
            "SELECT transfer_type, fee_type, fee_value, min_fee "
            "FROM transfer_fees "
            "WHERE transfer_type = ? "
            "  AND min_amount <= ? "
            "  AND (max_amount IS NULL OR max_amount >= ?) "
            "LIMIT 1",
            (transfer_type.lower(), amount, amount),
        ).fetchone()
    return dict(row) if row else None


def get_fx_rate(currency_code: str) -> dict | None:
    """Return the indicative FX rate to LKR for a given currency code."""
    with _conn() as c:
        row = c.execute(
            "SELECT currency_code, rate_to_lkr, updated_date "
            "FROM fx_rates WHERE currency_code = ?",
            (currency_code.upper(),),
        ).fetchone()
    return dict(row) if row else None


def get_all_fx_rates() -> list[dict]:
    """Return all FX rates (for display when no specific currency is requested)."""
    with _conn() as c:
        rows = c.execute(
            "SELECT currency_code, rate_to_lkr, updated_date FROM fx_rates ORDER BY currency_code"
        ).fetchall()
    return [dict(r) for r in rows]


# ── full rate-card tables (for public product pages) ─────────────────────────

def get_all_fd_rates() -> list[dict]:
    """Return all FD rate tiers ordered by tenure_months (for the FD product page)."""
    with _conn() as c:
        rows = c.execute(
            "SELECT tenure_months, annual_rate, early_withdrawal_penalty_rate "
            "FROM fd_rates ORDER BY tenure_months"
        ).fetchall()
    return [dict(r) for r in rows]


def get_all_loan_rates() -> list[dict]:
    """Return all loan rate rows (for a generic loans overview page if needed)."""
    with _conn() as c:
        rows = c.execute(
            "SELECT loan_type, annual_rate, max_tenure_months "
            "FROM loan_rates ORDER BY loan_type"
        ).fetchall()
    return [dict(r) for r in rows]


def get_all_pawning_rates() -> list[dict]:
    """Return all pawning rate rows ordered by carat (for the Pawning product page)."""
    with _conn() as c:
        rows = c.execute(
            "SELECT carat, rate_per_gram, ltv_percent, monthly_interest_rate "
            "FROM pawning_rates ORDER BY carat"
        ).fetchall()
    return [dict(r) for r in rows]


def get_all_transfer_fees() -> list[dict]:
    """Return all transfer fee rows (for the Transfers product page)."""
    with _conn() as c:
        rows = c.execute(
            "SELECT transfer_type, min_amount, max_amount, fee_type, fee_value, min_fee "
            "FROM transfer_fees ORDER BY transfer_type, min_amount"
        ).fetchall()
    return [dict(r) for r in rows]


# ── customer product queries (session_customer_id only) ──────────────────────

def get_my_fixed_deposits(customer_id: str) -> list[dict]:
    """Return all FD records for the authenticated customer. READ-ONLY."""
    with _conn() as c:
        rows = c.execute(
            "SELECT fd_id, principal, tenure_months, annual_rate, "
            "       start_date, maturity_date, maturity_amount, status "
            "FROM fixed_deposits WHERE customer_id = ? ORDER BY start_date DESC",
            (customer_id,),
        ).fetchall()
    return [dict(r) for r in rows]


def get_my_loans(customer_id: str) -> list[dict]:
    """Return all loan records for the authenticated customer. READ-ONLY."""
    with _conn() as c:
        rows = c.execute(
            "SELECT loan_id, loan_type, principal, outstanding_balance, "
            "       monthly_installment, tenure_months, start_date "
            "FROM loans WHERE customer_id = ? ORDER BY start_date DESC",
            (customer_id,),
        ).fetchall()
    return [dict(r) for r in rows]


def get_my_pawning_records(customer_id: str) -> list[dict]:
    """Return all pawning records for the authenticated customer. READ-ONLY."""
    with _conn() as c:
        rows = c.execute(
            "SELECT pawn_id, item_description, weight_grams, carat, "
            "       advance_amount, interest_rate, pawn_date, due_date, status "
            "FROM pawning_records WHERE customer_id = ? ORDER BY pawn_date DESC",
            (customer_id,),
        ).fetchall()
    return [dict(r) for r in rows]


def get_my_cards(customer_id: str) -> list[dict]:
    """Return all cards for the authenticated customer. READ-ONLY."""
    with _conn() as c:
        rows = c.execute(
            "SELECT card_id, card_type, masked_number, credit_limit, available_limit, status "
            "FROM cards WHERE customer_id = ? ORDER BY card_type",
            (customer_id,),
        ).fetchall()
    return [dict(r) for r in rows]
